"""Add missing style_id fields

Revision ID: 0056c2b404a5
Revises: de5c70ed0e30
Create Date: 2024-11-25 12:46:10.861107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0056c2b404a5'
down_revision: Union[str, None] = 'de5c70ed0e30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('style_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cart', 'good_style', ['style_id'], ['id'])
    op.add_column('order_item', sa.Column('style_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'order_item', 'good_style', ['style_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_item', type_='foreignkey')
    op.drop_column('order_item', 'style_id')
    op.drop_constraint(None, 'cart', type_='foreignkey')
    op.drop_column('cart', 'style_id')
    # ### end Alembic commands ###
