"""Add missing count field in cart_item table

Revision ID: 1148472710b9
Revises: ce27f9ed3050
Create Date: 2024-11-26 11:44:56.533220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1148472710b9'
down_revision: Union[str, None] = 'ce27f9ed3050'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart', 'count')
    # ### end Alembic commands ###
