"""Change file_id from uuid to str

Revision ID: ce27f9ed3050
Revises: 0056c2b404a5
Create Date: 2024-11-25 19:04:19.616562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ce27f9ed3050'
down_revision: Union[str, None] = '0056c2b404a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banner',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('image_id', sa.String(length=256), nullable=False),
    sa.Column('deleted', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('good', 'image_id',
               existing_type=mysql.CHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=32),
               type_=sa.String(length=256),
               existing_nullable=True)
    op.alter_column('good_detail', 'image_id',
               existing_type=mysql.CHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=32),
               type_=sa.String(length=256),
               existing_nullable=True)
    op.alter_column('good_style', 'image_id',
               existing_type=mysql.CHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=32),
               type_=sa.String(length=256),
               existing_nullable=True)
    op.alter_column('order', 'total_price',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('store', 'image_id',
               existing_type=mysql.CHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=32),
               type_=sa.String(length=256),
               existing_nullable=True)
    op.alter_column('user', 'avatar_id',
               existing_type=mysql.CHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=32),
               type_=sa.String(length=256),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'avatar_id',
               existing_type=sa.String(length=256),
               type_=mysql.CHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=32),
               existing_nullable=True)
    op.alter_column('store', 'image_id',
               existing_type=sa.String(length=256),
               type_=mysql.CHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=32),
               existing_nullable=True)
    op.alter_column('order', 'total_price',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('good_style', 'image_id',
               existing_type=sa.String(length=256),
               type_=mysql.CHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=32),
               existing_nullable=True)
    op.alter_column('good_detail', 'image_id',
               existing_type=sa.String(length=256),
               type_=mysql.CHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=32),
               existing_nullable=True)
    op.alter_column('good', 'image_id',
               existing_type=sa.String(length=256),
               type_=mysql.CHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=32),
               existing_nullable=True)
    op.drop_table('banner')
    # ### end Alembic commands ###
