"""Set columns nullable

Revision ID: de5c70ed0e30
Revises: d55df76bfd01
Create Date: 2024-11-24 11:59:19.600901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'de5c70ed0e30'
down_revision: Union[str, None] = 'd55df76bfd01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('address', 'postcode',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
               nullable=True)
    op.alter_column('address', 'comment',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
               nullable=True)
    op.alter_column('good', 'image_id',
               existing_type=mysql.CHAR(collation='utf8mb4_unicode_ci', length=32),
               nullable=True)
    op.alter_column('good_detail', 'text',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               nullable=True)
    op.alter_column('good_detail', 'image_id',
               existing_type=mysql.CHAR(collation='utf8mb4_unicode_ci', length=32),
               nullable=True)
    op.alter_column('good_style', 'description',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=512),
               nullable=True)
    op.alter_column('good_style', 'image_id',
               existing_type=mysql.CHAR(collation='utf8mb4_unicode_ci', length=32),
               nullable=True)
    op.alter_column('store', 'image_id',
               existing_type=mysql.CHAR(collation='utf8mb4_unicode_ci', length=32),
               nullable=True)
    op.alter_column('tag', 'description',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128),
               nullable=True)
    op.alter_column('user', 'phone_number',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128),
               nullable=True)
    op.alter_column('user', 'avatar_id',
               existing_type=mysql.CHAR(collation='utf8mb4_unicode_ci', length=32),
               nullable=True)
    op.alter_column('user', 'bio',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=256),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'bio',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=256),
               nullable=False)
    op.alter_column('user', 'avatar_id',
               existing_type=mysql.CHAR(collation='utf8mb4_unicode_ci', length=32),
               nullable=False)
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128),
               nullable=False)
    op.alter_column('user', 'phone_number',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
               nullable=False)
    op.alter_column('tag', 'description',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128),
               nullable=False)
    op.alter_column('store', 'image_id',
               existing_type=mysql.CHAR(collation='utf8mb4_unicode_ci', length=32),
               nullable=False)
    op.alter_column('good_style', 'image_id',
               existing_type=mysql.CHAR(collation='utf8mb4_unicode_ci', length=32),
               nullable=False)
    op.alter_column('good_style', 'description',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=512),
               nullable=False)
    op.alter_column('good_detail', 'image_id',
               existing_type=mysql.CHAR(collation='utf8mb4_unicode_ci', length=32),
               nullable=False)
    op.alter_column('good_detail', 'text',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               nullable=False)
    op.alter_column('good', 'image_id',
               existing_type=mysql.CHAR(collation='utf8mb4_unicode_ci', length=32),
               nullable=False)
    op.alter_column('address', 'comment',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
               nullable=False)
    op.alter_column('address', 'postcode',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
               nullable=False)
    # ### end Alembic commands ###
